[package]
name = "currencies"
version = "0.0.1"
edition = "2021"
authors = ["sam0x17"]
description = "The currencies crate provides a safe monetary data type and support for all ISO currencies as well as a variety of cryptocurrencies."
license = "MIT"
keywords = ["currencies", "currency", "money", "dollar", "monetary"]

[dependencies]
