[package]
name = "currencies"
version = "0.1.0"
edition = "2021"
authors = ["sam0x17"]

[dependencies]
num-integer = "0.1.45"
num-traits = "0.2.17"
primitive-types = { version = "0.12.2", features = ["num-traits"] }
uint = "0.9.5"
